# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zl26mgLO_8ERabuyR1M29qX8ncH8BAzE
"""

# ===================== 1. Dependency Import (Colab & PyCharm Dual Compatible) =====================
# Core data processing
import numpy as np
# Visualization for performance evaluation (native support in Colab)
import matplotlib.pyplot as plt
# Local GUI (only for PyCharm local run, auto-skipped in Colab)
import tkinter as tk
from tkinter import ttk, messagebox
# System environment detection
import sys

# Plot style configuration
plt.rcParams["axes.unicode_minus"] = False

# Colab-only inline plot setting (no syntax error in local PyCharm)
if 'google.colab' in sys.modules:
    try:
        from IPython import get_ipython
        get_ipython().run_line_magic('matplotlib', 'inline')
    except (ImportError, AttributeError):
        # 兜底兼容方案
        exec("%matplotlib inline")


# ===================== 2. Core Game Environment Class (Fixed Rules, Assignment Compliant) =====================
class MazeGame:
    def __init__(self):
        # Map configuration: 5x5 grid, discrete state space for basic Q-Learning
        self.grid_size = 5
        self.start_pos = (0, 0)  # Start point: top-left corner
        self.goal_pos = (4, 4)  # Goal (treasure): bottom-right corner, core objective
        self.traps = [(1, 1), (2, 3), (3, 0)]  # Fixed obstacle traps
        self.current_pos = self.start_pos  # Agent's current position
        self.max_steps = 30  # Max steps per episode, prevent infinite loop
        self.current_step = 0  # Steps taken in current episode

    # Reset game: call before each new episode, return to initial state
    def reset(self):
        self.current_pos = self.start_pos
        self.current_step = 0
        return self._pos_to_state(self.current_pos)

    # Convert (x,y) coordinates to discrete state ID (0-24, total 25 states)
    def _pos_to_state(self, pos):
        x, y = pos
        return x * self.grid_size + y

    # Core step function: input action, return [next_state, immediate_reward, episode_done_flag]
    def step(self, action):
        x, y = self.current_pos
        new_x, new_y = x, y

        # Action space: 4 discrete actions with fixed encoding
        if action == 0:  # Up: x decreases by 1, no out-of-bounds
            new_x = max(x - 1, 0)
        elif action == 1:  # Down: x increases by 1
            new_x = min(x + 1, self.grid_size - 1)
        elif action == 2:  # Left: y decreases by 1
            new_y = max(y - 1, 0)
        elif action == 3:  # Right: y increases by 1
            new_y = min(y + 1, self.grid_size - 1)

        # Increment step count
        self.current_step += 1
        new_pos = (new_x, new_y)
        # Reward function: hierarchical positive/negative rewards to guide optimal behavior
        reward = -1  # Default -1 per step, encourage shortest path
        done = False  # Episode completion flag

        # 1. Out-of-bounds penalty: negative reward for hitting grid boundary
        if new_pos == self.current_pos:
            reward = -10
        # 2. Trap penalty: high negative reward, end episode immediately
        elif new_pos in self.traps:
            reward = -50
            done = True
        # 3. Goal reward: high positive reward for reaching treasure, end episode
        elif new_pos == self.goal_pos:
            reward = 100
            done = True
        # 4. Max steps exceeded: end episode to prevent loop
        elif self.current_step >= self.max_steps:
            done = True

        # Update current position
        self.current_pos = new_pos
        # Return core data: next state, reward, episode done flag
        return self._pos_to_state(new_pos), reward, done


# ===================== 3. Q-Learning Agent Class (With Performance Tracking) =====================
class QLearningAgent:
    def __init__(self, state_size, action_size, alpha=0.1, gamma=0.95, epsilon=1.0):
        # Basic configuration
        self.state_size = state_size  # Total states: 5x5=25
        self.action_size = action_size  # Total actions: 4
        # Initialize Q-Table: [states x actions] array, all zeros initially
        # Stores the value of each state-action pair
        self.q_table = np.zeros((state_size, action_size))

        # Hyperparameter configuration (tunable for optimization experiments)
        self.alpha = alpha  # Learning rate: controls the magnitude of each Q-value update (0-1)
        self.gamma = gamma  # Discount factor: weights future rewards, closer to 1 = focus on long-term gain
        self.epsilon = epsilon  # Initial exploration rate: 1.0 = full random exploration at start
        self.epsilon_min = 0.01  # Minimum exploration rate: prevent zero exploration in late training
        self.epsilon_decay = 0.995  # Exploration decay rate: balance exploration & exploitation per episode

        # Performance tracking data (core data source for assignment report)
        self.reward_history = []  # Total reward per episode
        self.step_history = []  # Total steps per episode
        self.epsilon_history = []  # Exploration rate per episode

    # Action selection: epsilon-greedy strategy (core assignment requirement)
    def choose_action(self, state, is_test=False):
        # Test mode: full exploitation, select action with max Q-value (no random exploration)
        if is_test:
            return np.argmax(self.q_table[state, :])
        # Training mode: explore with epsilon probability, exploit with 1-epsilon probability
        if np.random.uniform(0, 1) < self.epsilon:
            return np.random.choice(self.action_size)  # Exploration: random action
        else:
            return np.argmax(self.q_table[state, :])  # Exploitation: action with max Q-value

    # Q-Table update: core Bellman Equation (algorithm core)
    def update_q_table(self, state, action, reward, next_state, done):
        # Current Q-value of the state-action pair
        q_current = self.q_table[state, action]
        # Target Q-value: only immediate reward if episode ends, else add discounted future max Q-value
        if done:
            q_target = reward
        else:
            q_target = reward + self.gamma * np.max(self.q_table[next_state, :])
        # Incremental Q-value update
        self.q_table[state, action] = q_current + self.alpha * (q_target - q_current)

    # Decay exploration rate: call after each episode, gradually reduce exploration
    def decay_epsilon(self):
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay
        # Record current epsilon for performance evaluation
        self.epsilon_history.append(self.epsilon)

    # Record episode data: call after each episode for performance tracking
    def record_episode_data(self, total_reward, total_step):
        self.reward_history.append(total_reward)
        self.step_history.append(total_step)


# ===================== 4. Model Performance Evaluation Module (Core for Assignment Report) =====================
# 4.1 Training Convergence Curve Plot: Reward, Steps, Epsilon (core report charts)
def plot_training_curve(agent, save_fig=False):
    """
    Plot training performance curves for assignment report
    :param agent: Trained QLearningAgent instance
    :param save_fig: Whether to save figure to local file
    """
    # Calculate moving average reward for smoother convergence trend
    window_size = 50
    smoothed_rewards = np.convolve(agent.reward_history, np.ones(window_size) / window_size, mode='valid')

    # Create 3 subplots
    fig, axes = plt.subplots(3, 1, figsize=(12, 15))

    # Subplot 1: Total Reward Curve
    axes[0].plot(agent.reward_history, label='Episode Total Reward', alpha=0.6, color='lightblue')
    axes[0].plot(range(window_size - 1, len(agent.reward_history)), smoothed_rewards,
                 label=f'{window_size}-Episode Moving Avg Reward', color='darkblue', linewidth=2)
    axes[0].set_title('1. Training Total Reward Trend', fontsize=14, fontweight='bold')
    axes[0].set_xlabel('Training Episodes', fontsize=12)
    axes[0].set_ylabel('Total Reward', fontsize=12)
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Subplot 2: Steps per Episode Curve
    axes[1].plot(agent.step_history, color='orange', alpha=0.7)
    axes[1].set_title('2. Training Steps per Episode Trend', fontsize=14, fontweight='bold')
    axes[1].set_xlabel('Training Episodes', fontsize=12)
    axes[1].set_ylabel('Total Steps per Episode', fontsize=12)
    axes[1].grid(True, alpha=0.3)

    # Subplot 3: Epsilon Decay Curve
    axes[2].plot(agent.epsilon_history, color='green', linewidth=2)
    axes[2].set_title('3. Training Exploration Rate (Epsilon) Decay', fontsize=14, fontweight='bold')
    axes[2].set_xlabel('Training Episodes', fontsize=12)
    axes[2].set_ylabel('Exploration Rate Epsilon', fontsize=12)
    axes[2].grid(True, alpha=0.3)

    plt.tight_layout()
    if save_fig:
        plt.savefig('model_performance_convergence_curve.png', dpi=300, bbox_inches='tight')
    plt.show()

    # Print quantitative evaluation metrics (direct use for report)
    print("=" * 50)
    print("Model Performance Quantitative Metrics")
    print("=" * 50)
    print(f"Total Training Episodes: {len(agent.reward_history)}")
    print(f"Avg Reward (First 100 Episodes): {np.mean(agent.reward_history[:100]):.2f}")
    print(f"Avg Reward (Last 100 Episodes): {np.mean(agent.reward_history[-100:]):.2f}")
    print(f"Avg Steps (First 100 Episodes): {np.mean(agent.step_history[:100]):.2f}")
    print(f"Avg Steps (Last 100 Episodes): {np.mean(agent.step_history[-100:]):.2f}")
    print(f"Minimum Steps (Optimal Path): {np.min(agent.step_history)}")
    print(f"Final Exploration Rate: {agent.epsilon:.4f}")
    print("=" * 50)


# 4.2 Hyperparameter Tuning Experiment (for assignment report)
def hyperparameter_tuning_experiment(train_episodes=1000):
    """
    Hyperparameter tuning comparison experiment
    Compare training performance of different learning rate and discount factor
    :param train_episodes: Number of training episodes
    """
    # Hyperparameter combinations to test
    alpha_list = [0.05, 0.1, 0.2]
    gamma_list = [0.9, 0.95, 0.99]
    game = MazeGame()
    state_size = game.grid_size * game.grid_size
    action_size = 4

    # Store reward history for different hyperparameters
    reward_results = {}

    # Iterate all hyperparameter combinations
    for alpha in alpha_list:
        for gamma in gamma_list:
            print(f"Training: Learning Rate alpha={alpha}, Discount Factor gamma={gamma}")
            agent = QLearningAgent(state_size, action_size, alpha=alpha, gamma=gamma)
            # Training loop
            for episode in range(train_episodes):
                state = game.reset()
                total_reward = 0
                done = False
                while not done:
                    action = agent.choose_action(state)
                    next_state, reward, done = game.step(action)
                    agent.update_q_table(state, action, reward, next_state, done)
                    state = next_state
                    total_reward += reward
                agent.record_episode_data(total_reward, game.current_step)
                agent.decay_epsilon()
            # Save results
            key = f"alpha={alpha}, gamma={gamma}"
            reward_results[key] = agent.reward_history

    # Plot comparison curve
    plt.figure(figsize=(14, 8))
    window_size = 50
    for key, reward_history in reward_results.items():
        smoothed_rewards = np.convolve(reward_history, np.ones(window_size) / window_size, mode='valid')
        plt.plot(range(window_size - 1, len(reward_history)), smoothed_rewards, label=key, linewidth=2)

    plt.title('Convergence Comparison of Different Hyperparameter Combinations', fontsize=16, fontweight='bold')
    plt.xlabel('Training Episodes', fontsize=14)
    plt.ylabel(f'{window_size}-Episode Moving Avg Reward', fontsize=14)
    plt.legend(fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig('hyperparameter_tuning_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()


# ===================== 5. Local GUI Interface (PyCharm Run, Single-Step Test Bug Fixed) =====================
class GameUI:
    def __init__(self, root, game, agent):
        self.root = root
        self.root.title("Q-Learning Maze Treasure Hunt Game")
        self.root.geometry("800x600")
        self.root.resizable(False, False)

        # Game and agent instances
        self.game = game
        self.agent = agent
        self.is_training = False
        self.is_trained = False  # Training status flag (core fix for single-step test bug)
        self.train_episodes = 1000
        self.current_episode = 0

        # UI component configuration
        self.cell_size = 80
        self.canvas = tk.Canvas(root, width=400, height=400, bg="white", bd=2, relief="solid")
        self.canvas.place(x=50, y=50)

        # Info panel
        self.info_frame = ttk.LabelFrame(root, text="Runtime Info")
        self.info_frame.place(x=500, y=50, width=250, height=400)

        # Info labels
        self.episode_label = ttk.Label(self.info_frame, text="Episodes: 0")
        self.episode_label.pack(pady=10, anchor="w")
        self.step_label = ttk.Label(self.info_frame, text="Current Steps: 0")
        self.step_label.pack(pady=10, anchor="w")
        self.reward_label = ttk.Label(self.info_frame, text="Total Reward: 0")
        self.reward_label.pack(pady=10, anchor="w")
        self.action_label = ttk.Label(self.info_frame, text="Current Action: -")
        self.action_label.pack(pady=10, anchor="w")
        self.epsilon_label = ttk.Label(self.info_frame, text="Exploration Rate: 1.00")
        self.epsilon_label.pack(pady=10, anchor="w")

        # Button panel
        self.btn_frame = ttk.Frame(root)
        self.btn_frame.place(x=50, y=480, width=700, height=80)

        self.train_btn = ttk.Button(self.btn_frame, text="Start Training", command=self.start_train)
        self.train_btn.grid(row=0, column=0, padx=20, pady=10)

        self.test_btn = ttk.Button(self.btn_frame, text="Single-Step Test", command=self.single_step_test)
        self.test_btn.grid(row=0, column=1, padx=20, pady=10)

        self.reset_btn = ttk.Button(self.btn_frame, text="Reset Game", command=self.reset_game)
        self.reset_btn.grid(row=0, column=2, padx=20, pady=10)

        self.plot_btn = ttk.Button(self.btn_frame, text="Plot Performance", command=self.plot_performance)
        self.plot_btn.grid(row=0, column=3, padx=20, pady=10)

        # Action name mapping
        self.action_names = ["Up", "Down", "Left", "Right"]
        # Episode total reward
        self.episode_reward = 0
        # Initial map render
        self.draw_map()

    # Draw grid map
    def draw_map(self):
        self.canvas.delete("all")
        # Draw grid cells
        for i in range(self.game.grid_size):
            for j in range(self.game.grid_size):
                x1 = j * self.cell_size
                y1 = i * self.cell_size
                x2 = x1 + self.cell_size
                y2 = y1 + self.cell_size
                # Fill color
                fill_color = "white"
                if (i, j) == self.game.start_pos:
                    fill_color = "#87CEEB"  # Start point: blue
                elif (i, j) == self.game.goal_pos:
                    fill_color = "#90EE90"  # Goal point: green
                elif (i, j) in self.game.traps:
                    fill_color = "#FF6347"  # Trap: red
                # Draw cell
                self.canvas.create_rectangle(x1, y1, x2, y2, fill=fill_color, outline="black")
        # Draw agent
        agent_x, agent_y = self.game.current_pos
        agent_x1 = agent_y * self.cell_size + 10
        agent_y1 = agent_x * self.cell_size + 10
        agent_x2 = agent_y * self.cell_size + self.cell_size - 10
        agent_y2 = agent_x * self.cell_size + self.cell_size - 10
        self.canvas.create_oval(agent_x1, agent_y1, agent_x2, agent_y2, fill="purple", tags="agent")

    # Update info panel
    def update_info(self, action=-1):
        self.episode_label.config(text=f"Episodes: {self.current_episode}")
        self.step_label.config(text=f"Current Steps: {self.game.current_step}")
        self.reward_label.config(text=f"Total Reward: {self.episode_reward:.2f}")
        self.action_label.config(text=f"Current Action: {self.action_names[action] if action != -1 else '-'}")
        self.epsilon_label.config(text=f"Exploration Rate: {self.agent.epsilon:.2f}")
        self.draw_map()
        self.root.update()

    # Reset game
    def reset_game(self):
        self.is_training = False
        self.current_episode = 0
        self.episode_reward = 0
        self.game.reset()
        # Reset Q-Table and training status
        self.agent.q_table = np.zeros((self.agent.state_size, self.agent.action_size))
        self.agent.epsilon = 1.0
        self.agent.reward_history = []
        self.agent.step_history = []
        self.agent.epsilon_history = []
        self.is_trained = False
        self.update_info()
        messagebox.showinfo("Reset", "Game and model have been reset successfully!")

    # Single-Step Test (core bug fix: training status validation)
    def single_step_test(self):
        # Core fix: block test if model is not trained
        if not self.is_trained:
            messagebox.showerror("Operation Error", "Please click 'Start Training' to complete model training first!")
            return
        # Core fix: test mode uses pure greedy strategy (no random exploration)
        state = self.game._pos_to_state(self.game.current_pos)
        action = self.agent.choose_action(state, is_test=True)
        # Execute action
        next_state, reward, done = self.game.step(action)
        self.episode_reward += reward
        # Update UI
        self.update_info(action)
        # Episode completion check
        if done:
            if self.game.current_pos == self.game.goal_pos:
                messagebox.showinfo("Test Complete", "✅ Agent successfully reached the treasure goal!")
            elif self.game.current_pos in self.game.traps:
                messagebox.showinfo("Test Complete", "❌ Agent hit a trap, episode ended!")
            else:
                messagebox.showinfo("Test Complete", "⏹️ Max steps exceeded, episode ended!")
            # Reset test environment
            self.game.reset()
            self.episode_reward = 0
            self.update_info()

    # Plot performance curve
    def plot_performance(self):
        if not self.is_trained:
            messagebox.showerror("Operation Error", "Please complete model training first to plot performance curves!")
            return
        plot_training_curve(self.agent, save_fig=True)

    # Start training
    def start_train(self):
        if self.is_training:
            return
        self.is_training = True
        self.train_btn.config(state="disabled")
        self.reset_game()
        self.current_episode = 0

        # Training loop
        for episode in range(self.train_episodes):
            self.current_episode = episode + 1
            state = self.game.reset()
            self.episode_reward = 0
            done = False

            while not done:
                # Select action
                action = self.agent.choose_action(state)
                # Execute action
                next_state, reward, done = self.game.step(action)
                # Accumulate reward
                self.episode_reward += reward
                # Update Q-Table
                self.agent.update_q_table(state, action, reward, next_state, done)
                # Switch state
                state = next_state
                # Visualize every 100 episodes to avoid UI lag
                if episode % 100 == 0:
                    self.update_info(action)
                    self.root.after(10)

            # Record episode data for performance evaluation
            self.agent.record_episode_data(self.episode_reward, self.game.current_step)
            # Decay exploration rate
            self.agent.decay_epsilon()
            # Print log every 100 episodes
            if episode % 100 == 0:
                print(
                    f"Episode:{episode + 1}, Total Reward:{self.episode_reward:.2f}, Exploration Rate:{self.agent.epsilon:.3f}")

        # Training complete
        self.is_training = False
        self.is_trained = True  # Mark training complete, unlock single-step test
        self.train_btn.config(state="normal")
        self.update_info()
        messagebox.showinfo("Training Complete",
                            f"✅ Q-Learning model training completed for {self.train_episodes} episodes!\nClick 'Single-Step Test' to test the agent, or 'Plot Performance' to view evaluation results.")


# ===================== 6. Program Entry (Dual Environment Compatible) =====================
if __name__ == "__main__":
    # Initialize game and agent
    game = MazeGame()
    state_size = game.grid_size * game.grid_size  # 25 discrete states
    action_size = 4  # 4 discrete actions
    agent = QLearningAgent(state_size, action_size)

    # Environment detection: Colab runs headless training + evaluation, local runs GUI
    if 'google.colab' in sys.modules:
        # ========== Google Colab Runtime Entry ==========
        print("Google Colab environment detected, starting headless training mode")
        train_episodes = 1000
        # Training loop
        for episode in range(train_episodes):
            state = game.reset()
            total_reward = 0
            done = False
            while not done:
                action = agent.choose_action(state)
                next_state, reward, done = game.step(action)
                agent.update_q_table(state, action, reward, next_state, done)
                state = next_state
                total_reward += reward
            # Record data
            agent.record_episode_data(total_reward, game.current_step)
            agent.decay_epsilon()
            # Print log every 100 episodes
            if episode % 100 == 0:
                print(f"Episode:{episode + 1}, Total Reward:{total_reward:.2f}, Exploration Rate:{agent.epsilon:.3f}")

        # Training complete, generate performance evaluation plots
        print("\nTraining completed, generating performance evaluation report")
        plot_training_curve(agent, save_fig=False)
        # Run hyperparameter tuning experiment (optional, bonus for report)
        print("\nStarting hyperparameter tuning comparison experiment")
        hyperparameter_tuning_experiment(train_episodes=1000)

    else:
        # ========== PyCharm Local Runtime Entry ==========
        root = tk.Tk()
        app = GameUI(root, game, agent)
        root.mainloop()